### ISSUE TITLE
Credits Issue (Reported by Multiple)

### ISSUE THREAD

**Issue by Abadima** [Abadima/modmail-plugins#2]
Apologies On This! I'm going to ensure all Credits are given to their rightful owners

**Comment by 6days9weeks** [comment]
Actions - https://github.com/6days9weeks/modmail-plugins/tree/master/action

**Comment by Abadima** [comment]
Added, Thanks.

> Actions - https://github.com/6days9weeks/modmail-plugins/tree/master/action
